name: release

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: Get source
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: Setup .NET Core 6.
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore packages.
      run: dotnet restore
    - name: Build all projects.
      run: dotnet build --configuration Release --no-restore

    - name: Unittests.
      run: dotnet test
      working-directory: ./test/NetTopologySuite.IO.VectorTiles.Tests/
    - name: Functional tests.
      run: dotnet run -c release
      working-directory: ./test/NetTopologySuite.IO.VectorTiles.Tests.Functional/
      
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/NetTopologySuite.IO.VectorTiles/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/NetTopologySuite.IO.VectorTiles.Mapbox/
    - name: Nuget Pack
      run: dotnet pack -c release
      working-directory: ./src/NetTopologySuite.IO.VectorTiles.GeoJson/
      
    - name: Nuget push Github
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/NetTopologySuite/index.json
      working-directory: ./src/

    - name: Nuget push Nuget
      run: dotnet nuget push **/*.nupkg --skip-duplicate -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json
      shell: bash
      working-directory: ./src/
